// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViveksHomoeoClinic.Data;

#nullable disable

namespace ViveksHomoeoClinic.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Billing", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BillingId"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("BillingId");

                    b.HasIndex("PatientId");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.CaseHistory", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<string>("Aversions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Desires")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyHistory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modalities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OccupationalHistory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Others")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PastHistory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PresentingComplaints")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Thermal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CaseId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("CaseHistories");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DesignationId"));

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DesignationId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<string>("BasisOfSelectionOfMed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PlanOfTreatment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.FollowUp", b =>
                {
                    b.Property<int>("FollowUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FollowUpId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("FollowUpDate")
                        .HasColumnType("date");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.HasKey("FollowUpId");

                    b.HasIndex("PrescriptionId")
                        .IsUnique();

                    b.ToTable("FollowUps");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GenderId");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Investigation", b =>
                {
                    b.Property<int>("InvestigationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvestigationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("InvestigationId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Investigations");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LoginFailureCount")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LoginId");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.MaritalStatus", b =>
                {
                    b.Property<int>("MaritalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaritalStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaritalStatusId");

                    b.ToTable("MaritalStatus");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Potency")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.HasKey("MedicineId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.MedicineBilling", b =>
                {
                    b.Property<int>("MedicineBillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MedicineBillingId"));

                    b.Property<int>("BillingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("MedicineBillingId");

                    b.HasIndex("BillingId");

                    b.HasIndex("MedicineId");

                    b.ToTable("MedicineBillings");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.MensturalHistory", b =>
                {
                    b.Property<int>("MensturalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MensturalHistoryId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Clots")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Flow")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LMP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Others")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MensturalHistoryId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("MensturalHistories");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.MentalGenerals", b =>
                {
                    b.Property<int>("MentalGeneralsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MentalGeneralsId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MentalGeneralsId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("MentalGenerals");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.ObstetricalHistory", b =>
                {
                    b.Property<int>("ObstetricalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ObstetricalHistoryId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ObstetricalHistoryId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("ObstetricalHistories");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AttenderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AttenderRelationship")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryContactNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecondaryContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PatientId");

                    b.HasIndex("GenderId");

                    b.HasIndex("MaritalStatusId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.PhysicalExamination", b =>
                {
                    b.Property<int>("PhysicalExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PhysicalExaminationId"));

                    b.Property<string>("Appearance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Chest")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Pulse")
                        .HasColumnType("int");

                    b.Property<string>("RespiratoryNote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SystemicExamination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.HasKey("PhysicalExaminationId");

                    b.HasIndex("PatientId");

                    b.ToTable("PhysicalExaminations");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.PhysicalGenerals", b =>
                {
                    b.Property<int>("PhysicalGeneralsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PhysicalGeneralsId"));

                    b.Property<string>("Appetite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Sleep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stool")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sweat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Thirst")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Urine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PhysicalGeneralsId");

                    b.HasIndex("CaseId")
                        .IsUnique();

                    b.ToTable("PhysicalGenerals");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PrescriptionDate")
                        .HasColumnType("date");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InvestigationId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("InvestigationId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.RoleMapping", b =>
                {
                    b.Property<int>("RoleMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleMapId"));

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RoleMapId");

                    b.HasIndex("LoginId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMapping");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CertificateNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("EducationQualification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PassOutYear")
                        .HasColumnType("int");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryContactNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecondaryContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("GenderId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StockId"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockId");

                    b.HasIndex("MedicineId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<string>("ModeOfToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("TokenNumber")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Token");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<DateTime>("DateOfVisit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("VisitId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Vitals", b =>
                {
                    b.Property<int>("VitalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VitalsId"));

                    b.Property<string>("BP_Dia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BP_Sys")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Pulse")
                        .HasColumnType("int");

                    b.Property<double>("Sugar")
                        .HasColumnType("double");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("VitalsId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Appointment", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Staff", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Billing", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.CaseHistory", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.CaseHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Diagnosis", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.FollowUp", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Prescription", "Prescription")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.FollowUp", "PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Investigation", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.Investigation", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.MedicineBilling", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Billing", "Billing")
                        .WithMany()
                        .HasForeignKey("BillingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billing");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.MensturalHistory", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.CaseHistory", "Case")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.MensturalHistory", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.MentalGenerals", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.CaseHistory", "Case")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.MentalGenerals", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.ObstetricalHistory", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.CaseHistory", "Case")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.ObstetricalHistory", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Patient", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.MaritalStatus", "MaritalStatus")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.Patient", "MaritalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("MaritalStatus");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.PhysicalExamination", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.PhysicalGenerals", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.CaseHistory", "Case")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.PhysicalGenerals", "CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Prescription", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Report", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Investigation", "Investigation")
                        .WithMany()
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.RoleMapping", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Staff", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Designation");

                    b.Navigation("Gender");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Stock", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Token", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.Token", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Visit", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ViveksHomoeoClinic.Models.EFModel.Vitals", b =>
                {
                    b.HasOne("ViveksHomoeoClinic.Models.EFModel.Patient", "Patient")
                        .WithOne()
                        .HasForeignKey("ViveksHomoeoClinic.Models.EFModel.Vitals", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
